# Generated by Django 3.0.5 on 2021-04-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='servicemenu',
            old_name='username',
            new_name='user',
        ),
    ]
