# Generated by Django 3.0.5 on 2021-04-21 14:51

import app.models
from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210421_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='service_opted',
            field=django_mysql.models.JSONField(default=app.models.default_json),
        ),
    ]
